### ISSUE TITLE
Add minimum styling to the main page

### ISSUE THREAD

**Issue by oxanayoxana** [arkency/find-open-source-mentor#10]
Bootstrap/ Material Design ?

**Comment by andrzejkrzywda** [comment]
This is one of those issues where I'd love to have them done, but I will probably not be a good mentor. Every styling framework I've used was a nightmare. But yeah, we need to some minimum styling, so whoever feels like they can suggest something, feel free to provide the PR.

**Comment by PyrinAndrii** [comment]
I'll take it))

**Comment by andrzejkrzywda** [comment]
@PyrinAndrii am I right that we now have the minimum styling thanks to you and we can conside this done?

**Comment by PyrinAndrii** [comment]
Yep, I think we should add more styling, but as for now it's minimum and it's enough:)

**Comment by andrzejkrzywda** [comment]
Great! Thank you @oxanayoxana and @PyrinAndrii 👍
