### ISSUE TITLE
List OSS projects where there is a chance to get some mentoring

### ISSUE THREAD

**Issue by andrzejkrzywda** [arkency/find-open-source-mentor#2]

**Comment by oxanayoxana** [comment]
Make form to submit oss projects. Can be made so, that logged in contributors see "add project" on a main page, once clicked it is shown their repositories on GitHub (as a pop-up window?) - and can just select those, which seems good for juniors to contribute to. (I personally don't know how to do that yet - maybe there is a better way - just comment what you think)

**Comment by skrix** [comment]
To my mind, the flow should be next:
- User sign-in/up via GitHub account
- User redirected to the home page with a list of already added projects and button "Add project"
- User press the button "Add project"
- User redirected to the page with a list of his projects retrieved from GitHub via api
- User click "Add" button on the project he wants to add
- User redirected to the form with prepopulated data about his project from GitHub
- User check all data and fill missing fields
- User clicks "Save project" button
- User redirected to the home page with a list of his projects and the already added new project

**Comment by oxanayoxana** [comment]
Would like to take it but will need help with github api

**Comment by andrzejkrzywda** [comment]
@skrix Thanks for an example how it can ideally work!

@oxanayoxana I think that for now, we'd be just fine if this feature works similarly as in https://github.com/arkency/find-open-source-mentor/issues/3 where we assumed the data will be introduced manually via Rails console. For the first release this should be fine, as we won't get that many projects yet to make it more friendly. Immediately after the first release, we will probably add a better scenario, following what @skrix has suggested.

So, for now, no need for Github integration.

**Comment by andrzejkrzywda** [comment]
It seems that @hkopij prepared a pull request related to this issue - https://github.com/arkency/find-open-source-mentor/pull/14

I haven't reviewed it yet.

**Comment by oxanayoxana** [comment]
Looks like first public release is ready)

**Comment by andrzejkrzywda** [comment]
@oxanayoxana we're close, but we still need some styling and heroku deploy

**Comment by andrzejkrzywda** [comment]
To my understanding it's closed by #14
