### ISSUE TITLE
Allow listing junior programmers who want to be shown public

### ISSUE THREAD

**Issue by andrzejkrzywda** [arkency/find-open-source-mentor#3]

**Comment by andrzejkrzywda** [comment]
The first, very basic implementation can be:

- create a model called JuniorDeveloper (or just Developer)
- create a controller with just one action: juniors/index
- create a view which just takes Junior.all and displays name

For the beginning we don't have to have a way of adding people via UI. We can do it from the Rails console- for those people who want it. For the first release it should be enough. Later we can add nicer UI for that - maybe an admin panel?

**Comment by hkopij** [comment]
I'll take care of that

**Comment by andrzejkrzywda** [comment]
Closed by #13
