### ISSUE TITLE
Slack invitation link is expired

### ISSUE THREAD

**Issue by htuerker** [arkency/find-open-source-mentor#32]
Hi folks!

I wanted to join you on Slack but the invitation link in the base README file is no longer active.

Is the channel still active?

**Comment by oxanayoxana** [comment]
Hi, @btuerker! Thanks, it might have expired. So, here you are https://join.slack.com/t/open-source-mentor/shared_invite/enQtODAwOTkzODcxOTA1LTllODUyMzcxZTk4MmZjZWFhM2IxOTUzYTU5N2UwNmFlNDhmY2MxOGM0NjA3OTBlMzIxNTYzNGJiYzU0ODQzZjE

Will update link in read me also.

Are you planning to take any issue? (Would be sooo great!)

**Comment by htuerker** [comment]
Thanks @oxanayoxana 👍

Of course, I'm planning to contribute. (You cannot guess how it's exciting to me)
